/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vew.insertion;

/**
 *
 * @author joseo
 */
import theme.colors.Pallet;

public class ProductlineEdit extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public ProductlineEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newProductline = new model.Bean.Productlines();
        WindowContainer = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        windowSubtitle = new javax.swing.JLabel();
        windowIcon = new javax.swing.JLabel();
        windowLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jP_BotaoCriarConta1 = new javax.swing.JPanel();
        jL_CriarConta1 = new javax.swing.JLabel();
        editArea = new javax.swing.JPanel();
        labelNameProductline = new javax.swing.JLabel();
        fieldLine1 = new javax.swing.JSeparator();
        textNameProductline = new javax.swing.JTextField();
        labelDescriptionProductline = new javax.swing.JLabel();
        fieldLine2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        labelNameProductline1 = new javax.swing.JLabel();

        newProductline.setHtmlDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nova Linha de Produtos");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        WindowContainer.setBackground(new java.awt.Color(112, 87, 241));
        WindowContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        WindowContainer.setForeground(new java.awt.Color(112, 87, 241));

        header.setBackground(new java.awt.Color(238, 238, 238));

        windowSubtitle.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        windowSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        windowSubtitle.setText("Adicione novas linhas e categorias de produtos para loja");

        windowIcon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        windowIcon.setForeground(new java.awt.Color(255, 255, 255));
        windowIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme/icons/icons_view/productline_64.png"))); // NOI18N

        windowLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        windowLabel.setForeground(new java.awt.Color(112, 87, 241));
        windowLabel.setText("Nova linha de produtos");

        closeButton.setFont(new java.awt.Font("Corbel Light", 1, 48)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme/icons/cancel_circle_violet_32.png"))); // NOI18N
        closeButton.setToolTipText("Fechar o sistema");
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(windowIcon)
                .addGap(31, 31, 31)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(windowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windowSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(windowIcon)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addComponent(windowLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(windowSubtitle))))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme/icons/icons_view/photo_128.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 87, 241));
        jLabel2.setText("Adicionar foto...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jP_BotaoCriarConta1.setBackground(new java.awt.Color(172, 252, 60));
        jP_BotaoCriarConta1.setForeground(new java.awt.Color(255, 255, 255));
        jP_BotaoCriarConta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jL_CriarConta1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jL_CriarConta1.setForeground(new java.awt.Color(152, 54, 252));
        jL_CriarConta1.setText("SALVAR");

        javax.swing.GroupLayout jP_BotaoCriarConta1Layout = new javax.swing.GroupLayout(jP_BotaoCriarConta1);
        jP_BotaoCriarConta1.setLayout(jP_BotaoCriarConta1Layout);
        jP_BotaoCriarConta1Layout.setHorizontalGroup(
            jP_BotaoCriarConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BotaoCriarConta1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jL_CriarConta1)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jP_BotaoCriarConta1Layout.setVerticalGroup(
            jP_BotaoCriarConta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_BotaoCriarConta1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jL_CriarConta1)
                .addGap(18, 18, 18))
        );

        editArea.setBackground(new java.awt.Color(255, 255, 255));

        labelNameProductline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNameProductline.setForeground(new java.awt.Color(102, 102, 102));
        labelNameProductline.setText("NOME DA LINHA DE PRODUTOS");

        fieldLine1.setForeground(new java.awt.Color(102, 102, 102));
        fieldLine1.setPreferredSize(new java.awt.Dimension(0, 1));
        fieldLine1.setRequestFocusEnabled(false);

        textNameProductline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textNameProductline.setForeground(new java.awt.Color(102, 102, 102));
        textNameProductline.setText("Digite o nome da linha de produtos");
        textNameProductline.setToolTipText("Digite seu nome completo");
        textNameProductline.setBorder(null);
        textNameProductline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameProductlineActionPerformed(evt);
            }
        });

        labelDescriptionProductline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelDescriptionProductline.setForeground(new java.awt.Color(102, 102, 102));
        labelDescriptionProductline.setText("DESCRIÇÃO DA LINHA");

        fieldLine2.setForeground(new java.awt.Color(102, 102, 102));
        fieldLine2.setPreferredSize(new java.awt.Dimension(0, 1));
        fieldLine2.setRequestFocusEnabled(false);

        jScrollPane2.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(250, 250, 250));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTextPane1.setText("Descreva a nova linha de produtos");
        jTextPane1.setToolTipText("Descreva a nova linha de produtos");
        jTextPane1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout editAreaLayout = new javax.swing.GroupLayout(editArea);
        editArea.setLayout(editAreaLayout);
        editAreaLayout.setHorizontalGroup(
            editAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editAreaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(editAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNameProductline)
                    .addComponent(fieldLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescriptionProductline)
                    .addComponent(fieldLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editAreaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(editAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNameProductline, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        editAreaLayout.setVerticalGroup(
            editAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editAreaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelNameProductline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNameProductline, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(labelDescriptionProductline)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelNameProductline1.setBackground(new java.awt.Color(255, 255, 255));
        labelNameProductline1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNameProductline1.setForeground(new java.awt.Color(255, 255, 255));
        labelNameProductline1.setText("IMAGEM ILUSTRATIVA");

        javax.swing.GroupLayout WindowContainerLayout = new javax.swing.GroupLayout(WindowContainer);
        WindowContainer.setLayout(WindowContainerLayout);
        WindowContainerLayout.setHorizontalGroup(
            WindowContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WindowContainerLayout.createSequentialGroup()
                .addComponent(editArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(WindowContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WindowContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jP_BotaoCriarConta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNameProductline1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WindowContainerLayout.setVerticalGroup(
            WindowContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WindowContainerLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(WindowContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WindowContainerLayout.createSequentialGroup()
                        .addComponent(editArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(WindowContainerLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelNameProductline1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jP_BotaoCriarConta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WindowContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WindowContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void textNameProductlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameProductlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameProductlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductlineEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductlineEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductlineEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductlineEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductlineEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WindowContainer;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel editArea;
    private javax.swing.JSeparator fieldLine1;
    private javax.swing.JSeparator fieldLine2;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jL_CriarConta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jP_BotaoCriarConta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelDescriptionProductline;
    private javax.swing.JLabel labelNameProductline;
    private javax.swing.JLabel labelNameProductline1;
    private model.Bean.Productlines newProductline;
    private javax.swing.JTextField textNameProductline;
    private javax.swing.JLabel windowIcon;
    private javax.swing.JLabel windowLabel;
    private javax.swing.JLabel windowSubtitle;
    // End of variables declaration//GEN-END:variables
}
